### ISSUE TITLE
Add Redux and typescript?

### ISSUE THREAD

**Issue by jaksatomovic** [0wczar/airframe-react#17]
Is there any hope we will see this in the future?

**Comment by jaksatomovic** [comment]
Pls, can I get any feedback?

**Comment by 0wczar** [comment]
@jaksatomovic Sorry for the late reply. Yes, typescript airframe will be available. I don't know about Redux yet. I will make Roadmap available soon. We'll be in touch.

**Comment by jaksatomovic** [comment]
@0wczar  Awesome! Thank You for your reply.  I have just one more question. Is there any chance You could tell me when will that be (typescript airframe, not redux)?
