### ISSUE TITLE
Standalone NPM package

### ISSUE THREAD

**Issue by Emnalyeriar** [0wczar/airframe-react#2]
Hey,
first of all - great work! I really love the look and feel of this admin dashboard.
I would like to try it out in an existing project and the best way to do it would be to just install it with NPM and import your components into my app. Any plans for this?
Waiting for the Next.js version :)

**Comment by n-kolodziej** [comment]
An npm package for this would be awesome!

**Comment by Lasvad** [comment]
agreed. I would love to embed this admin dashboard into my existing application.

**Comment by tigrish** [comment]
Our team is facing this issue right now, they're going "what? we have to implement all of these components???". NPM import would be ace! 🏆

**Comment by 0wczar** [comment]
> Waiting for the Next.js version :)
@Emnalyeriar Just Starter: https://github.com/webkom-co/airframe-next

> I would like to try it out in an existing project and the best way to do it would be to just install it with NPM and import your components into my app. Any plans for this?

@Emnalyeriar @n-kolodziej @Lasvad @tigrish Yes, we're working on it.

**Comment by 0wczar** [comment]
BTW; I will add Roadmap soon. Thank you for your feedback.

**Comment by npomfret** [comment]
Hi.  Does anyone have some practical advice on how I go about actually implementing an airframe-react app.  All I see is this repo and a sample site.  What steps do I take to put this into put own app?
