### ISSUE TITLE
Demo as Development Build?

### ISSUE THREAD

**Issue by zebulonj** [0wczar/airframe-react#3]
If the demo, which is beautiful, were published as a development build and therefore explorable using the React dev-tools... that would be an excellent way to help users understand the available components and relationships between those components.

**Comment by unski11ed** [comment]
You can launch a development build of the Demo by cloning this public repo. Publishing development to remote demo server would increase the required bandwidth (and loading times) a lot, which would affect the demo experience negatively.

Feel free to clone this repo and check it out on your local machine.

**Comment by zebulonj** [comment]
Huh. Didn't realize the demo was in this same repo.

**Comment by buncismamen** [comment]
@zebulonj could you close this issue if the issue is solved ?
