### ISSUE TITLE
Scss Overrides

### ISSUE THREAD

**Issue by scottshane** [0wczar/airframe-react#4]
How do you override style variables? For example, I would like to change some of the basic Bootstrap colors. Values added to styles/variables.scss or colors.scss don't seem to get picked up in the build.

**Comment by dyaacov** [comment]
Hi Scott,

Were you able to override $primary?

**Comment by scottshane** [comment]
No. We didn't end up going with airframe as a solution.

**Comment by dyaacov** [comment]
Any other suggested similar template?

**Comment by Abe-2** [comment]
I was able to override some bootstrap styles by placing them inside styles/bootstrap.scss file.
