### ISSUE TITLE
Adjust alignment on card header when input is present

### ISSUE THREAD

**Issue by stevecastaneda** [0wczar/airframe-react#5]
![image](https://user-images.githubusercontent.com/171488/63431001-7f2a9380-c3e3-11e9-9957-4e1436215357.png)

Probably would be better aligned along the bottom edge.  Seen in Chrome.

**Comment by scottshane** [comment]
you my consider creating an `app/styles/override.scss` to  adjusts some of  css opinions.

// app/styles/main.scss`.
```@import '~@owczar/dashboard-style--airframe/scss/style';
@import './overrides.scss';```

// overrides.scss
```label[for='leftCheckbox'].custom-control-label::before {
  top: 0;
}
label[for='leftRadio'].custom-control-label::before {
  top: 0;
}```
