### ISSUE TITLE
npm install failing - ESLint dependency

### ISSUE THREAD

**Issue by s3to87** [0wczar/airframe-react#57]
When trying to run npm install with a fresh cloned repo, i receive the following.
Does someone have an idea how I can solve this?
Many thanks in advance!

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: airframe-dashboard@0.1.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^4.19.1 || ^5.3.0" from eslint-config-airbnb@17.1.1
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^17.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\...\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2022-01-11T23_55_44_907Z-debug-0.log`

**Comment by furryboffin** [comment]
try to replace the version number of eslint in package.json with "*". Then run npm install again.

**Comment by s3to87** [comment]
Thank you, this solved the issue.

**Comment by Quangui-He** [comment]
I have the same issue,how to slove it,thank you
