### ISSUE TITLE
npm Install Error

### ISSUE THREAD

**Issue by LorenzoAppiadu** [0wczar/airframe-react#62]
code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/Marak/faker.js.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LorenzoDavid\AppData\Local\npm-cache\_logs\2022-10-14T19_23_28_644Z-debug-0.log
PS C:\Users\LorenzoDavid\Desktop\airframe-react> npm build:dev
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

 verbose stack Error: An unknown git error occurred
5537 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
5537 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
5537 verbose stack     at runMicrotasks (<anonymous>)
5537 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
5538 verbose cwd C:\Users\LorenzoDavid\Desktop\airframe-react
5539 verbose Windows_NT 10.0.19043
5540 verbose node v16.16.0
5541 verbose npm  v8.11.0
5542 error code 128
5543 error An unknown git error occurred
5544 error command git --no-replace-objects ls-remote ssh://git@github.com/Marak/faker.js.git
5545 error git@github.com: Permission denied (publickey).
5545 error fatal: Could not read from remote repository.
5545 error
5545 error Please make sure you have the correct access rights
5545 error and the repository exists.
5546 verbose exit 128
5547 timing npm Completed in 152194ms
5548 verbose unfinished npm timer reify 1665774988048
5549 verbose unfinished npm timer reify:loadTrees 1665774988064
5550 verbose code 128
5551 error A complete log of this run can be found in:
5551 error     C:\Users\LorenzoDavid\AppData\Local\npm-cache\_logs\2022-10-14T19_16_27_721Z-debug-0.log

**Comment by yellow-digital-labs** [comment]
I am also getting the same error

**Comment by 0wczar** [comment]
Sorry for silent. I just back from hospital.
Guys - can you help me with an update if you have time?

**Comment by maz2019** [comment]
Any update, I am also getting the same error

**Comment by SachiSamadhi** [comment]
I am getting this error while executing npm install @owczar/dashboard-style--airframe

ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://[git@github.com](mailto:git@github.com)/Marak/faker.js.git
npm ERR! [git@github.com](mailto:git@github.com): Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\pcc\AppData\Local\npm-cache_logs\2023-04-07T06_16_42_180Z-debug-0.log

How can I resolve this error?

**Comment by SachiSamadhi** [comment]
I am also getting the same error

**Comment by FunnyGoofy** [comment]
it is still a problem on Windows platform, any thoughts?

**Comment by jhonpaul77** [comment]
same error

**Comment by 0wczar** [comment]
Please try: `npm run start:dev`
