### ISSUE TITLE
npm install, errors....

### ISSUE THREAD

**Issue by LorenzoAppiadu** [0wczar/airframe-react#63]
npm install, errors....
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: airframe-dashboard@0.1.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^4.19.1 || ^5.3.0" from eslint-config-airbnb@17.1.1
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^17.1.0" from the root project      
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\admin\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2022-09-17T01_19_06_222Z-debug-0.log

_Originally posted by @DomainDevs in https://github.com/0wczar/airframe-react/issues/7#issuecomment-1249969213_

**Comment by CodeNinjaUsman** [comment]
Use `npm install --force`

**Comment by ManavTanna** [comment]
This issue occurs because of conflicting peerDependencies and thus `npm install` fails.
This issue can be solved by bypassing the conflict using `npm install --legacy-peer-deps`

**Comment by 0wczar** [comment]
Also you can try: `npm run start:dev`
